In [6]:
import numpy as np
import matplotlib.pyplot as plt
#.......................Now we need to solve this AT=B equation using Gauss seidel ........
def Gauss_seidel(A,B):
    key=0
    n=len(A)
    x=np.ones(n) #.................#initial guess as 1 for all the x
    x_0=np.ones(n)
    epc=10**(-9)
    while(key==0):
        for i in range(0,n):
            sum1=B[i]
            for j in range(0,n):
                if(i!=j):
                    sum1= sum1-A[i][j]*x_0[j]
            x[i]=sum1/A[i][i]
            if(abs((x[i]-x_0[i])/x[i])<epc):
                key=1
            x_0[i]=x[i]
    return x
#..........................End of Gauss_seidel....................
Nx=4
Ny=3
L=0.3
H=0.4
# dx=np.zeros(Nx+1)
# dy=np.zeros(Nx+1)
# dx[0]=L/Nx
# dy[0]=L/Ny
# for i in range(1,Nx+1):
#     dx[i]=dx[i-1]*1
# for i in range(1,Ny+1):
#     dy[i]=dy[i-1]*1
# cx=np.zeros(Nx+1)
# cy=np.zeros(Ny+1)
# node_x=np.zeros(Nx)
# node_y=np.zeros(Ny)
# for i in range(1,Nx+1):
#     cx[i]=cx[i-1]+dx[i]
# for i in range(0,Nx):
#     node_x[i]=(cx[i]+cx[i+1])/2
# for i in range(1,Ny+1):
#     cy[i]=cy[i-1]+dy[i]
# for i in range(0,Ny):
#     node_y[i]=(cy[i]+cy[i+1])/2 
# # [X,Y] =np.meshgrid(x,y)
# for i in range(0,Nx+1):
#     cx[i]=(cx[i]/cx[-1])*L
# for i in range(0,Nx+1):
#     cy[i]=(cy[i]/cy[-1])*H
# ..............................cx is storing face value cx[i] and node_x is giving cell center value ......

dx_1=L/Nx #### to avoid initial confusion we ignore streatching case ############ 
dy_1=L/Ny #### to avoid initial confusion we ignore streatching case ############
#..............................................
k= 1000
q=0
T1=100
T2=200
T3=100
T4=100
#Area=1
N=Nx*Ny
#..........................Need to create A and B matric to AT=B............. and find T using Gauss-Seidel
A=np.zeros((N,N) ,dtype=np.float32)
B=np.zeros(N,dtype=np.float32)
T=np.zeros(N,dtype=np.float32)
#.....................calculation of coefficient of A..................................
for i in range(0,N):
    for j in range(0,N):
        if(i==0): #1
            Aw=0
            Ae=k*dy_1/dx_1
            An=k*dx_1/dy_1
            As=0
            Sp=-(2*k*dy_1)/dx_1 -(2*k*dx_1)/dy_1
            Su=(q*dy_1*dx_1)+((2*k*dy_1)/dx_1)*T4+((2*k*dx_1)/dy_1)*T1
            Ap=Aw+Ae+An+As-Sp
            if(j==0):
                A[i][j]= Ap
            if(j==i+1):
                A[i][j]=-Ae
            if(j==Nx):
                A[i][j]=-An
            B[i]=Su
        elif(i==(Nx -1)):#3
            Aw=(k*dy_1)/dx_1
            Ae=0
            An=(k*dx_1)/dy_1
            As=0
            Sp=-(2*k*dy_1)/dx_1-(2*k*dx_1)/dy_1
            Su=(q*dy_1*dx_1) + ((2*k*dy_1)/dx_1)*T2 +((2*k*dx_1)/dy_1)*T1
            Ap=Aw+Ae+An+As-Sp
            if(j==i):
                A[i][j]=Ap
            if(j==i-1):
                A[i][j]=-Aw
            if(j==i+Nx):
                A[i][j]=-An
            B[i]=Su
        elif(i==(N-1)):#9
            Aw=(k*dy_1)/dx_1
            Ae=0
            An=0
            As=(k*dx_1)/dy_1
            Sp=-(2*k*dy_1)/dx_1-(2*k*dx_1)/dy_1
            Su=(q*dy_1*dx_1) + ((2*k*dy_1)/dx_1)*T2 +((2*k*dx_1)/dy_1)*T3
            Ap=Aw+Ae+An+As-Sp
            if(j==i):
                A[i][j]=Ap
            if(j==(i-1)):
                A[i][j]=-Aw
            if(j==(i-Nx)):
                A[i][j]=-As
            B[i]=Su
        elif(i==(N-Nx)):#7done
            Aw=0
            Ae=(k*dy_1)/dx_1
            An=0
            As=(k*dx_1)/dy_1
            Sp=-(2*k*dy_1)/dx_1-(2*k*dx_1)/dy_1
            Su=(q*dy_1*dx_1) + ((2*k*dy_1)/dx_1)*T4 +((2*k*dx_1)/dy_1)*T3
            Ap=Aw+Ae+An+As-Sp
            if(j==i):
                A[i][j]=Ap
            if(j==(i+1)):
                A[i][j]=-Ae
            if(j==(i-Nx)):
                A[i][j]=-As
            B[i]=Su
        elif(1<=i<=(Nx-2)):   #2done
            Aw=(k*dy_1)/dx_1
            Ae=(k*dy_1)/dx_1
            An=(k*dx_1)/dy_1
            As=0
            Sp=-(2*k*dx_1)/dy_1
            Su=(q*dy_1*dx_1) +((2*k*dx_1)/dy_1)*T1
            Ap=Aw+Ae+An+As-Sp
            if(j==i):
                A[i][j]=Ap
            if(j==i+1):
                A[i][j]=-Ae
            if(j==i-1):
                A[i][j]=-Aw
            if(j==i+Nx):
                A[i][j]=-An
            B[i]=Su
        elif(i%(Nx)==(Nx-1)):#6done 
            Aw=(k*dy_1)/dx_1
            Ae=0
            An=(k*dx_1)/dy_1
            As=(k*dx_1)/dy_1
            Sp=-(2*k*dy_1)/dx_1
            Su=(q*dy_1*dx_1) + ((2*k*dy_1)/dx_1)*T2 
            Ap=Aw+Ae+An+As-Sp
            if(j==i):
                A[i][j]=Ap
            if(j==(i+Nx)):
                A[i][j]=-An
            if(j==(i-Nx)):
                A[i][j]=-As
            if(j==(i-1)):
                A[i][j]=-Aw           
            B[i]=Su
        elif((N-Nx)<i<(N-1)):#8
            Aw=(k*dy_1)/dx_1
            Ae=(k*dy_1)/dx_1
            An=0
            As=(k*dx_1)/dy_1
            Sp=-(2*k*dx_1)/dy_1
            Su=(q*dy_1*dx_1) +((2*k*dx_1)/dy_1)*T3
            Ap=Aw+Ae+An+As-Sp
            if(j==i):
                A[i][i]=Ap
            if(j==i+1):
                A[i][j]=-Ae
            if(j==i-1):
                A[i][j]=-Aw
            if(j==(i-Nx)):
                A[i][j]=-As            
            B[i]=Su
        elif(i%(Nx-1)==1):#4
            Aw=0
            Ae=(k*dy_1)/dx_1
            An=(k*dx_1)/dy_1
            As=(k*dx_1)/dy_1
            Sp=-(2*k*dy_1)/dx_1
            Su=(q*dy_1*dx_1) + ((2*k*dy_1)/dx_1)*T4
            Ap=Aw+Ae+An+As-Sp
            if(j==i):
                A[i][i]=Ap
            if(j==i+1):
                A[i][j]=-Ae
            if(j==(i-Nx)):
                A[i][j]=-As
            if(j==(i+Nx)):
                A[i][j]=-An  
            B[i]=Su
        else:#5
            Aw=(k*dy_1)/dx_1
            Ae=(k*dy_1)/dx_1
            An=(k*dx_1)/dy_1
            As=(k*dx_1)/dy_1
            Sp=0
            Su=(q*dy_1*dx_1)
            Ap=Aw+Ae+An+As-Sp
            A[i][i]=Ap
            A[i][i+1]=-Ae
            A[i][i-1]=-Aw
            A[i][i+Nx]=-An
            A[i][i-Nx]=-As
            B[i]=Su
#print(A)
T=Gauss_seidel(A,B)
#print(T)
T_final=np.reshape(T, (Nx, Ny))
print(T_final)

# print(node_x)
# plt.plot(node_x*100,T)
# plt.show()
# #..............For contour...............
# node_xf=np.zeros(Nx)

[[102.65370775 109.71751543 123.63170792]
 [156.45830924 104.83865851 116.97405047]
 [137.2730234  172.91845088 102.65370803]
 [109.71751583 123.63170819 156.45830932]]
